blank_issues_enabled: true
contact_links:
  - name: Contributing guide
    url: https://github.com/LukeOfWales/motorsport-events/blob/main/CONTRIBUTING.md
    about: How to add an event source or make changes.
